# --------------------
# Core
# --------------------
spark.master spark://spark-master:7077
spark.serializer org.apache.spark.serializer.KryoSerializer

# --------------------
# Delta Lake
# --------------------
spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog

# --------------------
# S3 / SeaweedFS
# --------------------
spark.hadoop.fs.s3a.endpoint http://seaweedfs-s3:8333
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.connection.ssl.enabled false
spark.hadoop.fs.s3a.aws.credentials.provider com.amazonaws.auth.EnvironmentVariableCredentialsProvider

# --------------------
# Streaming
# --------------------
spark.sql.streaming.stateStore.providerClass org.apache.spark.sql.execution.streaming.state.RocksDBStateStoreProvider
spark.sql.streaming.checkpointLocation s3a://polyhorizon-streamingdata/checkpoints/ # check for the appropriate s3 store and correct checkpoints url

# --------------------
# S3 Committer (critical for streaming correctness)
# --------------------
spark.hadoop.fs.s3a.committer.name magic
spark.hadoop.fs.s3a.committer.magic.enabled true


  
